server:
  port: 8086

spring:
  application:
    name: api-gateway001
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ruta-usuarios
              uri: ${MS_USUARIOS_URL:http://ms-usuarios:8081}
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=1
            - id: ruta-metas
              uri: ${MS_NOTAS_METAS_URL:http://ms-notas-metas:8083}
              predicates:
                - Path=/api/metas/**
              filters:
                - StripPrefix=1
            - id: ruta-notas
              uri: ${MS_NOTAS_METAS_URL:http://ms-notas-metas:8083}
              predicates:
                - Path=/api/notas/**
              filters:
                - StripPrefix=1

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
