name: Deploy Notara Backend

on:
  push:
    branches: [deploy]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 60
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          495450559805.dkr.ecr.us-east-1.amazonaws.com

      - name: Build y Push ms-usuarios
        run: |
          docker build -t 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-ms-usuarios:latest ./ms-usuarios
          docker push 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-ms-usuarios:latest

      - name: Build y Push ms-canciones
        run: |
          docker build -t 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-ms-canciones:latest ./ms-canciones
          docker push 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-ms-canciones:latest

      - name: Build y Push api-gateway
        run: |
          docker build -t 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-api-gateway:latest ./api-gateway
          docker push 495450559805.dkr.ecr.us-east-1.amazonaws.com/notara-api-gateway:latest

      - name: Crear archivo .env
        run: |
          cat > $GITHUB_WORKSPACE/.env << ENVEOF
          DATA_EC2_IP=${{ secrets.DATA_EC2_IP }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
          SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
          ENVEOF

      - name: Deploy contenedores
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down || true
          docker system prune -af || true
          docker compose pull
          docker compose up -d

      - name: Verificar contenedores
        run: docker ps
